package com.rainax.ytdownloader

import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.downloader.Downloader
import org.schabi.newpipe.extractor.downloader.Request
import org.schabi.newpipe.extractor.downloader.Response
import org.schabi.newpipe.extractor.exceptions.ReCaptchaException
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.StreamType
import java.net.HttpURLConnection
import java.net.URL

/**
 * Fast YouTube info in pure Java/Kotlin (NewPipe Extractor), the way apps like SnapTube read YouTube:
 * no Python start-up, usually well under a second. It only fills the download sheet (title, thumbnail,
 * qualities with sizes, subtitles). The download itself is still done by yt-dlp, and whenever this
 * extractor fails the app quietly falls back to yt-dlp.
 */
object FastExtractor {

    @Volatile private var ready = false

    @Synchronized
    private fun init() {
        if (ready) return
        NewPipe.init(HttpDownloader)
        ready = true
    }

    /** Single YouTube videos and Shorts only (playlists, live streams and other sites use yt-dlp). */
    fun supports(url: String): Boolean {
        val u = url.lowercase()
        val yt = u.contains("youtube.com/watch") || u.contains("youtube.com/shorts/") || u.contains("youtu.be/")
        return yt && !u.contains("music.youtube.com")
    }

    /** Blocking. Throws on any problem (the caller then uses yt-dlp). */
    fun fetch(url: String): PreviewState {
        init()
        val info = StreamInfo.getInfo(ServiceList.YouTube, url)
        if (info.streamType != StreamType.VIDEO_STREAM) error("Not a normal video")

        val duration = info.duration.toInt()
        val progressive = mutableMapOf<Int, Long>()
        val videoOnly = mutableMapOf<Int, Long>()
        var bestAudio = 0L
        var bestM4a = 0L

        fun bytes(len: Long?, bitrate: Int): Long = when {
            len != null && len > 0 -> len
            bitrate > 0 && duration > 0 -> bitrate.toLong() / 8 * duration
            else -> 0L
        }

        for (v in info.videoStreams.orEmpty()) {
            val h = v.height.takeIf { it > 0 } ?: v.resolution.substringBefore('p').toIntOrNull() ?: continue
            val size = bytes(v.itagItem?.contentLength, v.bitrate)
            progressive[h] = maxOf(progressive[h] ?: 0L, size)
        }
        for (v in info.videoOnlyStreams.orEmpty()) {
            val h = v.height.takeIf { it > 0 } ?: v.resolution.substringBefore('p').toIntOrNull() ?: continue
            val size = bytes(v.itagItem?.contentLength, v.bitrate)
            videoOnly[h] = maxOf(videoOnly[h] ?: 0L, size)
        }
        for (a in info.audioStreams.orEmpty()) {
            val br = if (a.averageBitrate > 0) a.averageBitrate * 1000 else a.bitrate
            val size = bytes(a.itagItem?.contentLength, br)
            bestAudio = maxOf(bestAudio, size)
            if (a.format?.suffix == "m4a") bestM4a = maxOf(bestM4a, size)
        }
        if (progressive.isEmpty() && videoOnly.isEmpty() && bestAudio == 0L) error("No streams")

        val subs = info.subtitles.orEmpty()
            .distinctBy { it.languageTag + it.isAutoGenerated }
            .take(30)
            .map { s ->
                val name = runCatching { s.locale.getDisplayLanguage(java.util.Locale.ENGLISH) }.getOrNull()
                    ?.takeIf { it.isNotBlank() } ?: s.displayLanguageName ?: s.languageTag
                SubtitleOption(s.languageTag, if (s.isAutoGenerated) "$name (auto)" else name)
            }
            .distinctBy { it.code }

        val built = InfoFetcher.buildChoices(progressive, videoOnly, bestAudio, bestM4a, duration, subs)

        val thumbUrl = info.thumbnails
            .sortedBy { kotlin.math.abs((it.height.takeIf { h -> h > 0 } ?: 360) - 360) }
            .firstOrNull()?.url
        val thumb = thumbUrl?.let { InfoFetcher.loadBitmap(it) }

        return PreviewState(
            title = info.name,
            subtitle = subtitleLine(info.uploaderName, duration),
            thumb = thumb,
            quick = built.quick,
            all = built.all,
            subtitles = built.subs
        )
    }

    private fun subtitleLine(uploader: String?, seconds: Int): String {
        val parts = mutableListOf<String>()
        if (!uploader.isNullOrBlank()) parts += uploader
        if (seconds > 0) {
            val h = seconds / 3600
            val m = (seconds % 3600) / 60
            val s = seconds % 60
            parts += if (h > 0) "%d:%02d:%02d".format(h, m, s) else "%d:%02d".format(m, s)
        }
        return parts.joinToString("  •  ")
    }

    /** Minimal HTTP client for the extractor (no extra library needed). */
    private object HttpDownloader : Downloader() {
        private const val UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"

        override fun execute(request: Request): Response {
            val con = URL(request.url()).openConnection() as HttpURLConnection
            try {
                con.requestMethod = request.httpMethod()
                con.connectTimeout = 15_000
                con.readTimeout = 20_000
                con.instanceFollowRedirects = true
                con.setRequestProperty("User-Agent", UA)
                request.headers()?.forEach { (name, values) ->
                    if (name != null) {
                        con.setRequestProperty(name, values.firstOrNull() ?: "")
                        values.drop(1).forEach { con.addRequestProperty(name, it) }
                    }
                }
                val body = request.dataToSend()
                if (body != null) {
                    con.doOutput = true
                    con.outputStream.use { it.write(body) }
                }
                val code = con.responseCode
                if (code == 429) throw ReCaptchaException("reCaptcha Challenge requested", request.url())
                val stream = if (code >= 400) con.errorStream else con.inputStream
                val text = stream?.use { it.readBytes().toString(Charsets.UTF_8) }
                val headers = con.headerFields.filterKeys { it != null }
                return Response(code, con.responseMessage, headers, text, con.url.toString())
            } finally {
                con.disconnect()
            }
        }
    }
}
